[package]
name = "server"
version = "0.1.0"
authors = ["marcmaniez <marc.maniez@gmail.com>"]

[dependencies]
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
iron = "0.5.*"
